# Generated by Django 4.1.1 on 2022-09-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_reviews_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
